# Group Project - Cat Image Classification

## Group 4: Isaiah Martinez, Joycelyn Tuazon
## Mrs. Lord - Comp 542 Machine Learning

# Guides that may provide insight

In [ ]:
#Count objects
#https://new.pythonforengineers.com/blog/image-and-video-processing-in-python/

#Basic outline for image classificaiton. See youtube video too.
#https://www.youtube.com/watch?v=il8dMDlXrIE
#https://github.com/computervisioneng/image-classification-python-scikit-learn/blob/master/main.py

#Image classification with Tensorflow and Keras
#https://www.tensorflow.org/tutorials/images/classification

#Load and Preprocess Images
#https://www.tensorflow.org/tutorials/load_data/images

## Kaggle Examples with Code to look at

In [ ]:
# Good to model after
# Also in the Conv2D section
# https://www.kaggle.com/code/shaileshkakade/image-classification-cat-dog-panda

# plots vertical/horizontal edge detection
# https://www.kaggle.com/code/dianalaveena/cnn-keras-image-classification
# Consider KNN

## CNN Examples

In [ ]:
# https://www.kaggle.com/code/dongduongminh/cnn-deep-learning-image-classification
# https://www.kaggle.com/code/nasrinjahanripa/animal-images-classification-cnn
# https://www.kaggle.com/code/corneliustantius/classification-with-keras-cnn
# SEE `explaining-line.ipynb`

## ConNeXt

In [ ]:
# https://www.kaggle.com/code/chenjiarui2018/cats-dogs-and-pandas-convnext#3.-Model

## VGG16 CNN

In [ ]:
# https://www.kaggle.com/code/arpita12/cat-dog-panda
# https://www.kaggle.com/code/rwt1998/animal-classification
# https://www.kaggle.com/code/atmaraiprince/animal-image-dataset
# https://www.kaggle.com/code/kkamal2003/animal-images-cnn

## Conv 2D

In [ ]:
# https://www.kaggle.com/code/shaileshkakade/image-classification-cat-dog-panda
# https://www.kaggle.com/code/etienne1976/animal-image-classification-with-keras
# https://www.kaggle.com/code/bygbrains/dog-cat-pandas-image-classifier
# https://www.kaggle.com/code/dianalaveena/cnn-keras-image-classification#5.-Model-Building-and-Compilation

## Res Net 50

In [ ]:
# https://www.kaggle.com/code/nasrinjahanripa/animal-images-classification-cnn
# https://www.kaggle.com/code/profmedo/image-classification-cnn-with-resnet
# https://www.kaggle.com/code/kkamal2003/resnet-for-classification
# https://www.kaggle.com/code/arshnoor7389/resnet-for-classification

## OpenAI - CLIP
## Dont use CLIP as project. CLIP may provide insight or be compared to, but not submitted for grade

In [ ]:
# GITHUB LINK:
# https://github.com/openai/CLIP/blob/main/model-card.md#model-card-clip
# https://www.kaggle.com/code/kimchanyoung/zero-shot-prediction-using-openai-s-clip

# Individual Work:

In [ ]:
#Resize all images into arrays
import projHelper as pjH

cats_resized = pjH.getResizedGrayscaleFlattenedArrays("animals_cleaned/cats/")
dogs_resized = pjH.getResizedGrayscaleFlattenedArrays("animals_cleaned/dogs/")
panda_resized = pjH.getResizedGrayscaleFlattenedArrays("animals_cleaned/panda/")

#each image is an array of 750,000 (500 * 500 * 3)
print(cats_resized[0])
print(cats_resized[0].shape)

#Resized cat/dog/panda images into a single array of size 994/990/968
print("# cat imgs", len(cats_resized))
print("# dog imgs", len(dogs_resized))
print("# panda imgs", len(panda_resized))
print("total dataset size is", len(cats_resized) + len(dogs_resized) + len(panda_resized))

#14 second runtime

In [ ]:
#Save the modified images into animals_cleaned_GS directory
import projHelper as pjH

pjH.saveModifiedImages("animals_cleaned/cats/", "animals_cleaned_GS/cats/")

In [ ]:
#create labels and combine data into a single array

#insert labels into array
labels = ["cat"] * len(cats_resized) + ["dog"] * len(dogs_resized) + ["panda"] * len(panda_resized)

#combine data into a single array
data_resized = [*cats_resized, *dogs_resized, *panda_resized]

#compare sizes of labels and data_resized since they should be the same
#expected: True
print(len(data_resized) == len(labels))

#testing labels
#expected: cat cat dog dog panda panda
print(labels[0], labels[993], labels[994], labels[1983], labels[1984], labels[2951])

In [ ]:
#split the data into train and test
from sklearn.model_selection import train_test_split

#80/20 split
xTrain, xTest, yTrain, yTest = train_test_split(data_resized, labels, test_size = 0.2)

print(len(xTrain), xTrain, "\n")
print(len(yTrain), yTrain, "\n")
print(len(xTest), xTest, "\n")
print(len(yTest), yTest, "\n")

#each array in xTrain and xTest is of type: float32
#the max value from xTrain and xTest is 255

In [ ]:
#########################################################
#                       Notes                           #
#########################################################

# print out Accuracy, Specificity, Recall, F1 Score. If possible, also the Confusion Matrix

# Analyze model for Over/Underfitting so that it can be reduced

# Use/find an alg to balance the class vs not class for images (Cat vs Non-Cat)

# possibly convert rgb images to grayscale using GLCM
#      might want to compare rgb images and grayscale

## Isaiah Martinez

## SVM Classifier

### Testing the svm classifier with no parameter changes

In [ ]:
#feed dataset into model

from sklearn import svm

clf = svm.SVC(kernel = 'linear', cache_size = 2000, max_iter = 5000, decision_function_shape = 'ovr', verbose = True)
clf.fit(xTrain, yTrain)

#15 minute runtime 750,000

#8 minute runtime 250,000

In [ ]:
#predict and obtain metrics

from sklearn.metrics import accuracy_score, f1_score, precision_score, recall_score

yPred = clf.predict(xTest)

acc = accuracy_score(yTest, yPred)
f1 = f1_score(yTest, yPred, average = 'weighted')
prec = precision_score(yTest, yPred, average = 'weighted')
recall = recall_score(yTest, yPred, average = 'weighted')

print(acc, f1, prec, recall)

#4 minute runtime (750,000)

#metrics:
#0.5617597292724196 0.570465072568459 0.591411754950014 0.5617597292724196

#2 minute runtime (250,000)

#metrics:
#0.44839255499153974 0.4560295854772547 0.4798984919706284 0.44839255499153974

### Pipeline + GridSearch

In [ ]:
###     Final Pipeline
from sklearn import svm
from sklearn.pipeline import Pipeline
from sklearn.model_selection import GridSearchCV
from sklearn.preprocessing import MinMaxScaler

pipeline = Pipeline([
    ('scaler', MinMaxScaler()),
    ('classifier', svm.SVC(cache_size = 16000, max_iter = 5000, decision_function_shape = 'ovr', verbose = True))
])

params = {
    'classifier__C' : [5, 1]
}

gridSearch = GridSearchCV(pipeline, params, cv = 5, n_jobs = 1, verbose = 4)

gridSearch.fit(xTrain, yTrain)

#1750 minute runtime (initial 750,000) (250 fits)
#100 minute runtime   (initial 250,000) (1 fit)
#417 minute runtime   (initial 250,000) (15 fits)
#1051 minute runtime   (initial 250,000) (45 fits)

In [ ]:
#print the best params and best model found from Grid Search
gridSearchParams = gridSearch.best_params_
gridSearchModel = gridSearch.best_estimator_

print(gridSearchParams, gridSearchModel)

In [ ]:
#prediction and metrics

from sklearn.metrics import accuracy_score, f1_score, precision_score, recall_score

yPred = gridSearchModel.predict(xTest)

acc = accuracy_score(yTest, yPred)
f1 = f1_score(yTest, yPred, average = 'weighted')
prec = precision_score(yTest, yPred, average = 'weighted')
recall = recall_score(yTest, yPred, average = 'weighted')

print(acc, f1, prec, recall)
#4 minute runtime

#initial run stats:
#0.5854483925549916 0.5885099209700294 0.5983072203381199 0.5854483925549916

#12 minute runtime 1 fit

#initial run stats: 1 fit
#0.6091370558375635 0.6054727828929725 0.6030864613210003 0.6091370558375635

#12 minute runtime 15 fits

#initial run stats: 1 fit
#0.6328257191201354 0.6299543290220251 0.6287454462588863 0.6328257191201354

In [ ]:
#Confusion Matrix

import matplotlib.pyplot as plt
from sklearn.metrics import ConfusionMatrixDisplay, confusion_matrix

cm = confusion_matrix(yTest, yPred, labels = gridSearchModel.classes_)
disp = ConfusionMatrixDisplay(confusion_matrix = cm, display_labels = gridSearchModel.classes_)
disp.plot()
plt.show()

## Zero-Shot Prediction CLIP

In [ ]:
# GITHUB LINK:              https://github.com/openai/CLIP/blob/main/model-card.md#model-card-clip
# Example code from Kaggle: https://www.kaggle.com/code/kimchanyoung/zero-shot-prediction-using-openai-s-clip

### Sample

#### ViT-B/32

In [ ]:
import torch
import clip
from PIL import Image
import numpy as np

device = "cuda" if torch.cuda.is_available() else "cpu"
model, preprocess = clip.load("ViT-B/32", device = device)

img = preprocess(Image.open("animals_cleaned/cats/cats_00001.jpg")).unsqueeze(0).to(device)

animals = ['cat', 'dog', 'panda']

text = clip.tokenize(animals).to(device)

with torch.no_grad():
    imageFeats = model.encode_image(img)
    textFeats = model.encode_text(text)

    logitsPerImg, logitsPerText = model(img, text)
    probs = np.array(logitsPerImg.softmax(dim = -1).cpu().numpy())

label = np.argmax(probs[0])

print(probs[0][label])
print(animals[label])
print(probs[0])

#### RN50x16

In [ ]:
import torch
import clip
from PIL import Image
import numpy as np

device = "cuda" if torch.cuda.is_available() else "cpu"
model, preprocess = clip.load("RN50x16", device = device)

img = preprocess(Image.open("animals_cleaned/cats/cats_00001.jpg")).unsqueeze(0).to(device)

animals = ['cat', 'dog', 'panda']

text = clip.tokenize(animals).to(device)

with torch.no_grad():
    imageFeats = model.encode_image(img)
    textFeats = model.encode_text(text)

    logitsPerImg, logitsPerText = model(img, text)
    probs = np.array(logitsPerImg.softmax(dim = -1).cpu().numpy())

label = np.argmax(probs[0])

print(probs[0][label])
print(animals[label])

### On All Data

In [1]:
#gather all filepaths to all images
from os import listdir
from os.path import isfile, join

catFiles = [f for f in listdir("animals_cleaned/cats/") if isfile(join("animals_cleaned/cats/", f))]
dogFiles = [f for f in listdir("animals_cleaned/dogs/") if isfile(join("animals_cleaned/dogs/", f))]
pandaFiles = [f for f in listdir("animals_cleaned/panda/") if isfile(join("animals_cleaned/panda/", f))]

print(catFiles)
print(len(catFiles))

['cats_00001.jpg', 'cats_00002.jpg', 'cats_00003.jpg', 'cats_00004.jpg', 'cats_00005.jpg', 'cats_00006.jpg', 'cats_00007.jpg', 'cats_00008.jpg', 'cats_00009.jpg', 'cats_00010.jpg', 'cats_00011.jpg', 'cats_00012.jpg', 'cats_00013.jpg', 'cats_00014.jpg', 'cats_00015.jpg', 'cats_00016.jpg', 'cats_00017.jpg', 'cats_00018.jpg', 'cats_00019.jpg', 'cats_00020.jpg', 'cats_00021.jpg', 'cats_00022.jpg', 'cats_00023.jpg', 'cats_00024.jpg', 'cats_00025.jpg', 'cats_00026.jpg', 'cats_00027.jpg', 'cats_00028.jpg', 'cats_00029.jpg', 'cats_00030.jpg', 'cats_00031.jpg', 'cats_00033.jpg', 'cats_00034.jpg', 'cats_00035.jpg', 'cats_00036.jpg', 'cats_00037.jpg', 'cats_00038.jpg', 'cats_00039.jpg', 'cats_00040.jpg', 'cats_00041.jpg', 'cats_00042.jpg', 'cats_00043.jpg', 'cats_00044.jpg', 'cats_00045.jpg', 'cats_00046.jpg', 'cats_00047.jpg', 'cats_00048.jpg', 'cats_00049.jpg', 'cats_00050.jpg', 'cats_00051.jpg', 'cats_00052.jpg', 'cats_00053.jpg', 'cats_00054.jpg', 'cats_00055.jpg', 'cats_00056.jpg', 'cats_000

In [2]:
#add the entire path to the images

for i in range(len(catFiles)):
    catFiles[i] = "animals_cleaned/cats/" + catFiles[i]

for i in range(len(dogFiles)):
    dogFiles[i] = "animals_cleaned/dogs/" + dogFiles[i]

for i in range(len(pandaFiles)):
    pandaFiles[i] = "animals_cleaned/panda/" + pandaFiles[i]

In [3]:
allFiles = [*catFiles, *dogFiles, *pandaFiles]

print(allFiles)
print(len(allFiles))

['animals_cleaned/cats/cats_00001.jpg', 'animals_cleaned/cats/cats_00002.jpg', 'animals_cleaned/cats/cats_00003.jpg', 'animals_cleaned/cats/cats_00004.jpg', 'animals_cleaned/cats/cats_00005.jpg', 'animals_cleaned/cats/cats_00006.jpg', 'animals_cleaned/cats/cats_00007.jpg', 'animals_cleaned/cats/cats_00008.jpg', 'animals_cleaned/cats/cats_00009.jpg', 'animals_cleaned/cats/cats_00010.jpg', 'animals_cleaned/cats/cats_00011.jpg', 'animals_cleaned/cats/cats_00012.jpg', 'animals_cleaned/cats/cats_00013.jpg', 'animals_cleaned/cats/cats_00014.jpg', 'animals_cleaned/cats/cats_00015.jpg', 'animals_cleaned/cats/cats_00016.jpg', 'animals_cleaned/cats/cats_00017.jpg', 'animals_cleaned/cats/cats_00018.jpg', 'animals_cleaned/cats/cats_00019.jpg', 'animals_cleaned/cats/cats_00020.jpg', 'animals_cleaned/cats/cats_00021.jpg', 'animals_cleaned/cats/cats_00022.jpg', 'animals_cleaned/cats/cats_00023.jpg', 'animals_cleaned/cats/cats_00024.jpg', 'animals_cleaned/cats/cats_00025.jpg', 'animals_cleaned/cats/ca

In [4]:
#Make the Confusion Matrix manually

import numpy as np

#initalize as empty 3x3 matrix and update as we make predictions
#read columns in order: cat, dog, panda     as prediction
#read rows in order:    cat, dog, panda     as actual
# i.e. cm[ACTUAL, PREDICTED]
#       eg. cm[1,2] means the actual animal was a dog while the predicted was a panda
cmViT = np.zeros((3,3), dtype = 'int')

print(cmViT)
print(type(cmViT))

[[0 0 0]
 [0 0 0]
 [0 0 0]]
<class 'numpy.ndarray'>


#### ViT-B/32

In [5]:
#run all the data and obtain the confusion matrix and probabilities for each 

import projHelper as pjH

cmViT, probabilitiesCats = pjH.getCMProbs(0, catFiles, cmViT, 0)
cmViT, probabilitiesDogs = pjH.getCMProbs(0, dogFiles, cmViT, 1)
cmViT, probabilitiesPanda = pjH.getCMProbs(0, pandaFiles, cmViT, 2)

In [6]:
print(cmViT)
print(probabilitiesCats[0])
print(probabilitiesDogs[0])
print(probabilitiesPanda[0])

[[2 0 0]
 [0 2 0]
 [0 0 2]]
0.9885767
0.99884665
0.99997103


#### RN50x16

In [ ]:
#initialize same as cmViT
cmRN = np.zeros((3,3), dtype = 'int')

In [ ]:
#run all the data and obtain the confusion matrix and probabilities for each 

cmRN, probabilitiesCats = pjH.getCMProbs(1, catFiles, cmRN, 0)
cmRN, probabilitiesDogs = pjH.getCMProbs(1, dogFiles, cmRN, 1)
cmRN, probabilitiesPanda = pjH.getCMProbs(1, pandaFiles, cmRN, 2)

## Joycelyn Tuazon

In [7]:
#Code here...

import keras
import projHelper as pjH
import pandas as pd

