# Group Project - Cat Image Classification

## Group 4: Isaiah Martinez, Joycelyn Tuazon
## Mrs. Lord - Comp 542 Machine Learning

# Notes, Familiarization, and Sample Code

In [1]:
import projHelper as pjH

extremeSizes = pjH.calculateExtremeSizes("animals_cleaned")
print(extremeSizes[0], "\tMaxWidth")
print(extremeSizes[1], "\tMinWidth")
print(extremeSizes[2], "\tMaxHeight")
print(extremeSizes[3], "\tMinHeight")

(1600, 1200) 	MaxWidth
(55, 75) 	MinWidth
(1600, 1200) 	MaxHeight
(94, 69) 	MinHeight


In [2]:
#Search for an image of size 500,500 within the cats folder

matches = pjH.imgSizeMatch([500, 500], "animals/cats/")

#there are none so we should see an empty list
print(matches)

[]


In [3]:
#now we're going to utilize keras for gaining insights into our images
import keras

img = keras.preprocessing.image.load_img("animals/cats/cats_00001.jpg")
#Notice the image from keras is of type PIL
print(type(img))
print(img.format)
print(img.mode)
print(img.size)

#img.show()

<class 'PIL.JpegImagePlugin.JpegImageFile'>
JPEG
RGB
(500, 374)


In [4]:
#show how resizing the image selected works

#notice this image has one dimension of size less than 500,500
image = img.resize([500,500])
#image.show()

In [5]:
#Search for an image of size 100, 87 within the panda folder

matches = pjH.imgSizeMatch([100, 87], "animals/panda/")

#there is exactly one
print(matches)

#Using the found filename, we will stretch the image out to 500,500 and see what happens when we resize it
#notice this image has both dimensions of size less than 500,500

img2 = keras.preprocessing.image.load_img("animals/panda/panda_00478.jpg")
#img2.show()

image2 = img2.resize([500,500])
#image2.show()

['panda_00478.jpg']


In [6]:
#Search for an image of size 1600, 1200 within the panda folder

matches = pjH.imgSizeMatch([1600, 1200], "animals/panda/")

#there is exactly one
print(matches)

#Using the found filename, we will stretch the image out to see what happens when we resize it
#notice this image has both dimensions of size greater than 500,500

img3 = keras.preprocessing.image.load_img("animals/panda/panda_00880.jpg")
#img3.show()

image3 = img3.resize([500,500])
#image3.show()

['panda_00880.jpg']


In [7]:
#Find Avg dimensions of all images
avgDims = pjH.avgDims("animals_cleaned")
print(avgDims)

(431.78523035230353, 372.25271002710025)


In [8]:
import numpy as np
image3Array = np.asarray(image3)
print(image3Array)

[[[154 158 128]
  [131 152 106]
  [ 76 114  60]
  ...
  [121 143 159]
  [125 146 167]
  [125 145 168]]

 [[111 133 110]
  [ 80 111  71]
  [118 155 109]
  ...
  [128 151 174]
  [138 160 188]
  [141 163 192]]

 [[ 58 100  80]
  [138 176 141]
  [187 218 181]
  ...
  [144 167 201]
  [145 168 205]
  [149 172 210]]

 ...

 [[ 20  41  50]
  [ 18  39  50]
  [ 24  44  54]
  ...
  [ 78  71  52]
  [ 66  63  47]
  [ 59  60  47]]

 [[ 24  44  51]
  [ 20  40  51]
  [ 28  47  58]
  ...
  [ 68  63  45]
  [ 59  58  44]
  [ 51  53  41]]

 [[ 28  47  55]
  [ 23  43  55]
  [ 33  52  64]
  ...
  [ 57  53  37]
  [ 51  52  38]
  [ 47  49  40]]]


# Guides that may provide insight

In [9]:
#Count objects
#https://new.pythonforengineers.com/blog/image-and-video-processing-in-python/

#Basic outline for image classificaiton. See youtube video too.
#https://www.youtube.com/watch?v=il8dMDlXrIE
#https://github.com/computervisioneng/image-classification-python-scikit-learn/blob/master/main.py

#Image classification with Tensorflow and Keras
#https://www.tensorflow.org/tutorials/images/classification

#Load and Preprocess Images
#https://www.tensorflow.org/tutorials/load_data/images

## Kaggle Examples with Code to look at

In [10]:
# Good to model after
# Also in the Conv2D section
# https://www.kaggle.com/code/shaileshkakade/image-classification-cat-dog-panda

# plots vertical/horizontal edge detection
# https://www.kaggle.com/code/dianalaveena/cnn-keras-image-classification
# Consider KNN

## CNN Examples

In [11]:
# https://www.kaggle.com/code/dongduongminh/cnn-deep-learning-image-classification
# https://www.kaggle.com/code/nasrinjahanripa/animal-images-classification-cnn
# https://www.kaggle.com/code/corneliustantius/classification-with-keras-cnn
# SEE `explaining-line.ipynb`

## ConNeXt

In [12]:
# https://www.kaggle.com/code/chenjiarui2018/cats-dogs-and-pandas-convnext#3.-Model

## VGG16 CNN

In [13]:
# https://www.kaggle.com/code/arpita12/cat-dog-panda
# https://www.kaggle.com/code/rwt1998/animal-classification
# https://www.kaggle.com/code/atmaraiprince/animal-image-dataset
# https://www.kaggle.com/code/kkamal2003/animal-images-cnn

## Conv 2D

In [14]:
# https://www.kaggle.com/code/shaileshkakade/image-classification-cat-dog-panda
# https://www.kaggle.com/code/etienne1976/animal-image-classification-with-keras
# https://www.kaggle.com/code/bygbrains/dog-cat-pandas-image-classifier
# https://www.kaggle.com/code/dianalaveena/cnn-keras-image-classification#5.-Model-Building-and-Compilation

## Res Net 50

In [15]:
# https://www.kaggle.com/code/nasrinjahanripa/animal-images-classification-cnn
# https://www.kaggle.com/code/profmedo/image-classification-cnn-with-resnet
# https://www.kaggle.com/code/kkamal2003/resnet-for-classification
# https://www.kaggle.com/code/arshnoor7389/resnet-for-classification

## OpenAI - CLIP
## Dont use CLIP as project. CLIP may provide insight or be compared to, but not submitted for grade

In [16]:
# GITHUB LINK:
# https://github.com/openai/CLIP/blob/main/model-card.md#model-card-clip
# https://www.kaggle.com/code/kimchanyoung/zero-shot-prediction-using-openai-s-clip

# Sample Code applying the dataset

In [17]:
#Following the Loading and Preprocessing Tensorflow tutorial from the above code
import tensorflow as tf

batch_size = 32
img_height = 500
img_width = 500

train_ds = tf.keras.utils.image_dataset_from_directory(
  directory="animals_cleaned/",
  validation_split=0.2,
  subset="training",
  seed=123,
  image_size=(img_height, img_width),
  batch_size=batch_size)

#3 classes are cat/dog/panda
#2362 ~~ 2361.6 = 2952 * 0.8

Found 2952 files belonging to 3 classes.
Using 2362 files for training.


In [18]:
from keras.datasets import mnist
from PIL import Image as im

(X_train, Y_train), (X_test, Y_test) = mnist.load_data()

print(X_train[0])

img4 = im.fromarray(X_train[0])

#img4.show()

[[  0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0
    0   0   0   0   0   0   0   0   0   0]
 [  0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0
    0   0   0   0   0   0   0   0   0   0]
 [  0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0
    0   0   0   0   0   0   0   0   0   0]
 [  0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0
    0   0   0   0   0   0   0   0   0   0]
 [  0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0
    0   0   0   0   0   0   0   0   0   0]
 [  0   0   0   0   0   0   0   0   0   0   0   0   3  18  18  18 126 136
  175  26 166 255 247 127   0   0   0   0]
 [  0   0   0   0   0   0   0   0  30  36  94 154 170 253 253 253 253 253
  225 172 253 242 195  64   0   0   0   0]
 [  0   0   0   0   0   0   0  49 238 253 253 253 253 253 253 253 253 251
   93  82  82  56  39   0   0   0   0   0]
 [  0   0   0   0   0   0   0  18 219 253 253 253 253 253 198 18

# Individual Work:

In [19]:
#Resize all images into arrays

cats_resized = pjH.getResizedFlattenedArrays("animals_cleaned/cats/")
dogs_resized = pjH.getResizedFlattenedArrays("animals_cleaned/dogs/")
panda_resized = pjH.getResizedFlattenedArrays("animals_cleaned/panda/")

#each image is an array of 750,000 (500 * 500 * 3)
print(cats_resized[0])
print(cats_resized[0].shape)

#Resized cat/dog/panda images into a single array of size 994/990/968
print("# cat imgs", len(cats_resized))
print("# dog imgs", len(dogs_resized))
print("# panda imgs", len(panda_resized))

[ 80. 131. 162. ...  52.  35.  19.]
(750000,)
# cat imgs 994
# dog imgs 990
# panda imgs 968


In [20]:
#create labels and combine data into a single array

#insert labels into array
labels = ["cat"] * len(cats_resized) + ["dog"] * len(dogs_resized) + ["panda"] * len(panda_resized)

#combine data into a single array
data_resized = [*cats_resized, *dogs_resized, *panda_resized]

#compare sizes of labels and data_resized since they should be the same
#expected: True
print(len(data_resized) == len(labels))

#testing labels
#expected: cat cat dog dog panda panda
print(labels[0], labels[993], labels[994], labels[1983], labels[1984], labels[2951])

True
cat cat dog dog panda panda


In [21]:
#split the data into train and test
from sklearn.model_selection import train_test_split

#80/20 split
xTrain, xTest, yTrain, yTest = train_test_split(data_resized, labels, test_size = 0.2)

print(len(xTrain), xTrain, "\n")
print(len(yTrain), yTrain, "\n")
print(len(xTest), xTest, "\n")
print(len(yTest), yTest, "\n")

2361 [array([148., 121.,  91., ..., 236., 240., 239.], dtype=float32), array([250., 255., 254., ..., 241., 235., 235.], dtype=float32), array([12., 15.,  8., ..., 49., 41., 39.], dtype=float32), array([33., 28., 24., ..., 99., 91., 70.], dtype=float32), array([226., 219., 193., ..., 237., 220., 204.], dtype=float32), array([ 81.,  62.,  64., ..., 229., 251., 249.], dtype=float32), array([56., 46., 37., ..., 62., 63., 83.], dtype=float32), array([74., 73., 39., ..., 49., 43., 27.], dtype=float32), array([ 86.,  88.,  85., ..., 233., 235., 234.], dtype=float32), array([ 53.,  26.,   6., ..., 162., 122.,  97.], dtype=float32), array([ 92.,  86.,  90., ..., 171., 163., 178.], dtype=float32), array([142., 117.,  60., ..., 217., 183., 156.], dtype=float32), array([121., 105.,  79., ...,  60., 101., 123.], dtype=float32), array([ 5.,  2.,  9., ..., 87., 82., 79.], dtype=float32), array([ 95.,  83.,  59., ..., 184., 192., 213.], dtype=float32), array([195., 193., 181., ...,  16.,  15.,  11.], 

In [22]:
#########################################################
#                       Notes                           #
#########################################################

# print out Accuracy, Specificity, Recall, F1 Score. If possible, also the Confusion Matrix

# Analyze model for Over/Underfitting so that it can be reduced

# Use/find an alg to balance the class vs not class for images (Cat vs Non-Cat)

# possibly convert rgb images to grayscale using GLCM
#      might want to compare rgb images and grayscale

In [23]:
# #Confusion Matrix
# from sklearn.metrics import ConfusionMatrixDisplay, confusion_matrix

# cm = confusion_matrix([Y TEST DATA], [Y PREDICTIONS FROM MODEL], labels = [MODEL].classes_)
# disp = ConfusionMatrixDisplay(confusion_matrix = cm, display_labels = [MODEL].classes_)
# disp.plot()
# plt.show()

#This is the code that I ran to obtain the Confusion Matrix for SVM

## Isaiah Martinez

## SVM Classifier

In [24]:
#feed dataset into model

from sklearn import svm

clf = svm.SVC(kernel = 'linear', cache_size = 2000, max_iter = 5000, decision_function_shape = 'ovo', verbose = True)
clf.fit(xTrain, yTrain)

[LibSVM]

c:\Python310\lib\site-packages\sklearn\svm\_base.py:299: ConvergenceWarning: Solver terminated early (max_iter=5000).  Consider pre-processing your data with StandardScaler or MinMaxScaler.
  warnings.warn(


SVC(cache_size=2000, decision_function_shape='ovo', kernel='linear',
    max_iter=5000, verbose=True)

In [25]:
###     Final Pipeline

## Joycelyn Tuazon

In [26]:
#Code here...