# Group Project - Cat Image Classification

## Group 4: Isaiah Martinez, Joycelyn Tuazon
## Mrs. Lord - Comp 542 Machine Learning

# 1) Data Pre-Processing

In [1]:
import projHelper as pjH

extremeSizes = pjH.calculateExtremeSizes()
print(extremeSizes[0], "\tMaxWidth")
print(extremeSizes[1], "\tMinWidth")
print(extremeSizes[2], "\tMaxHeight")
print(extremeSizes[3], "\tMinHeight")

2023-10-10 16:04:26.403619: I tensorflow/core/platform/cpu_feature_guard.cc:182] This TensorFlow binary is optimized to use available CPU instructions in performance-critical operations.
To enable the following instructions: AVX2 FMA, in other operations, rebuild TensorFlow with the appropriate compiler flags.


(1600, 1200) 	MaxWidth
(78, 120) 	MinWidth
(1600, 1200) 	MaxHeight
(100, 87) 	MinHeight


In [2]:
#Search for an image of size 500,500 within the cats folder

matches = pjH.imgSizeMatch([500, 500], "animals/cats/")

#there are none so we should see an empty list
print(matches)

[]


In [3]:
#now we're going to utilize keras for gaining insights into our images
import keras

img = keras.preprocessing.image.load_img("animals/cats/cats_00001.jpg")
#Notice the image from keras is of type PIL
print(type(img))
print(img.format)
print(img.mode)
print(img.size)

img.show()

<class 'PIL.JpegImagePlugin.JpegImageFile'>
JPEG
RGB
(500, 374)


In [4]:
#show how resizing the image selected works

#notice this image has one dimension of size less than 500,500
image = img.resize([500,500])
image.show()

In [5]:
#Search for an image of size 100, 87 within the panda folder

matches = pjH.imgSizeMatch([100, 87], "animals/panda/")

#there is exactly one
print(matches)

#Using the found filename, we will stretch the image out to 500,500 and see what happens when we resize it
#notice this image has both dimensions of size less than 500,500

img2 = keras.preprocessing.image.load_img("animals/panda/panda_00478.jpg")
img2.show()

image2 = img2.resize([500,500])
image2.show()

['panda_00478.jpg']


In [6]:
#Search for an image of size 1600, 1200 within the panda folder

matches = pjH.imgSizeMatch([1600, 1200], "animals/panda/")

#there is exactly one
print(matches)

#Using the found filename, we will stretch the image out to see what happens when we resize it
#notice this image has both dimensions of size greater than 500,500

img3 = keras.preprocessing.image.load_img("animals/panda/panda_00880.jpg")
img3.show()

image3 = img3.resize([500,500])
image3.show()

['panda_00880.jpg']


In [7]:
#Find Avg dimensions of all images
avgDims = pjH.avgDims()
print(avgDims)

(431.90066666666667, 371.62166666666667)


In [8]:
import numpy as np
image3Array = np.asarray(image3)
print(image3Array)

[[[154 158 128]
  [131 152 106]
  [ 76 114  60]
  ...
  [121 143 159]
  [125 146 167]
  [125 145 168]]

 [[111 133 110]
  [ 80 111  71]
  [118 155 109]
  ...
  [128 151 174]
  [138 160 188]
  [141 163 192]]

 [[ 58 100  80]
  [138 176 141]
  [187 218 181]
  ...
  [144 167 201]
  [145 168 205]
  [149 172 210]]

 ...

 [[ 20  41  50]
  [ 18  39  50]
  [ 24  44  54]
  ...
  [ 78  71  52]
  [ 66  63  47]
  [ 59  60  47]]

 [[ 24  44  51]
  [ 20  40  51]
  [ 28  47  58]
  ...
  [ 68  63  45]
  [ 59  58  44]
  [ 51  53  41]]

 [[ 28  47  55]
  [ 23  43  55]
  [ 33  52  64]
  ...
  [ 57  53  37]
  [ 51  52  38]
  [ 47  49  40]]]


# Examples that may provide insight

In [9]:
#Count objects
#https://new.pythonforengineers.com/blog/image-and-video-processing-in-python/

#Basic outline for image classificaiton. See youtube video too.
#https://www.youtube.com/watch?v=il8dMDlXrIE
#https://github.com/computervisioneng/image-classification-python-scikit-learn/blob/master/main.py

#Image classification with Tensorflow and Keras
#https://www.tensorflow.org/tutorials/images/classification

#Load and Preprocess Images
#https://www.tensorflow.org/tutorials/load_data/images

In [10]:
#Following the Loading and Preprocessing Tensorflow tutorial from the above code
import tensorflow as tf

batch_size = 32
img_height = 500
img_width = 500

train_ds = tf.keras.utils.image_dataset_from_directory(
  directory="animals/",
  validation_split=0.2,
  subset="training",
  seed=123,
  image_size=(img_height, img_width),
  batch_size=batch_size)

#3 classes are cat/dog/panda
#2400 = 3000 * 0.8

Found 3000 files belonging to 3 classes.
Using 2400 files for training.


In [11]:
from keras.datasets import mnist
from PIL import Image as im

(X_train, Y_train), (X_test, Y_test) = mnist.load_data()

print(X_train[0])

img4 = im.fromarray(X_train[0])

#img4.show()

[[  0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0
    0   0   0   0   0   0   0   0   0   0]
 [  0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0
    0   0   0   0   0   0   0   0   0   0]
 [  0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0
    0   0   0   0   0   0   0   0   0   0]
 [  0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0
    0   0   0   0   0   0   0   0   0   0]
 [  0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0
    0   0   0   0   0   0   0   0   0   0]
 [  0   0   0   0   0   0   0   0   0   0   0   0   3  18  18  18 126 136
  175  26 166 255 247 127   0   0   0   0]
 [  0   0   0   0   0   0   0   0  30  36  94 154 170 253 253 253 253 253
  225 172 253 242 195  64   0   0   0   0]
 [  0   0   0   0   0   0   0  49 238 253 253 253 253 253 253 253 253 251
   93  82  82  56  39   0   0   0   0   0]
 [  0   0   0   0   0   0   0  18 219 253 253 253 253 253 198 18